### ISSUE TITLE
Loading spatial in two separate connections causes some queries to hang

### ISSUE THREAD

**Issue by cpcloud** [duckdb/duckdb-spatial#629]
Here's a fully reproducible example:

```python
import tempfile
from pathlib import Path

import duckdb

con1 = duckdb.connect()
con1.install_extension("spatial")
con1.load_extension("spatial")

con2 = duckdb.connect()
con2.load_extension("spatial")

with tempfile.TemporaryDirectory() as tmpdir:
    out = Path(tmpdir) / "data.gpkg"
    con1.execute(f"COPY (SELECT 1 as x) TO '{out!s}' (FORMAT GDAL, DRIVER 'GPKG')")
```

This seems to only hand with the GPKG driver. If you comment out `con2.load_extension("spatial")` the query finishes as expected.

**Comment by cpcloud** [comment]
Passing a filename to `connect` also allows the script to finish.

**Comment by cpcloud** [comment]
This isn't a problem with DuckDB 1.2.2, seems only to be an issue with DuckDB 1.3.x.

**Comment by cpcloud** [comment]
Confirmed it's a problem in both 1.3.0 and 1.3.1.

**Comment by cpcloud** [comment]
@Mytherin Would love to see that fix in 1.3.2 if possible!

**Comment by Maxxen** [comment]
Hello! Ive done some more investigation and actually narrowed it down to an issue with spatial. I've pushed a fix in #632. Thanks for the great reproduction script!

**Comment by cpcloud** [comment]
@Maxxen Thanks!

Did this get released into the spatial extension yet? I'm still seeing the issue.

**Comment by Maxxen** [comment]
No, but v1.3.2 is currently building!
